apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubediscovery-company
  namespace: argocd
spec:
  description: Deploys de landingpage e docs da empresa
  sourceRepos:
    - https://github.com/kubediscovery/kubediscovery.git
  destinations:
    - namespace: kubediscovery
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
